### ISSUE TITLE
Cannot read property 'upgradeElement' of undefined

### ISSUE THREAD

**Issue by klappenbach** [payalabs/scalajs-react-mdl#2]
In my [project](https://github.com/gabbah/scalajs-react-mdl-test) , after running fastOptJS in sbt, and opening the [web page](https://github.com/gabbah/scalajs-react-mdl-test/blob/0.6.x/scalajs-tutorial-fastopt.html), I get the following error in the browser console as a result of trying to use a simple mdl button as given in your example code:

MaterialComponent.scala:19 Uncaught TypeError: Cannot read property 'upgradeElement' of undefined$c_Lcom_payalabs_scalajs_react_mdl_MaterialComponent$$anonfun$com$payalabs$scalajs$react$mdl$MaterialComponent$$upgrade$1.apply$mcV$sp__V @ MaterialComponent.scala:19$c_Lcom_payalabs_scalajs_react_mdl_MaterialComponent$$anonfun$com$payalabs$scalajs$react$mdl$MaterialComponent$$upgrade$1.apply__O @ MaterialComponent.scala:19(anonymous function) @ Callback.scala:33$c_sjsr_AnonFunction0.apply__O @ AnonFunctions.scala:10(anonymous function) @ ReactComponentB.scala:413$c_sjsr_AnonFunction1.apply__O__O @ AnonFunctions.scala:15MaterialComponent_componentDidMount @ ReactComponentB.scala:414_assign.notifyAll @ scala-js-tutorial-jsdeps.js:839ON_DOM_READY_QUEUEING.close @ scala-js-tutorial-jsdeps.js:13403Mixin.closeAll @ scala-js-tutorial-jsdeps.js:17555Mixin.perform @ scala-js-tutorial-jsdeps.js:17502batchedMountComponentIntoNode @ scala-js-tutorial-jsdeps.js:11684Mixin.perform @ scala-js-tutorial-jsdeps.js:17489ReactDefaultBatchingStrategy.batchedUpdates @ scala-js-tutorial-jsdeps.js:9589batchedUpdates @ scala-js-tutorial-jsdeps.js:15150ReactMount._renderNewRootComponent @ scala-js-tutorial-jsdeps.js:11837ReactMount__renderNewRootComponent @ scala-js-tutorial-jsdeps.js:12864ReactMount._renderSubtreeIntoContainer @ scala-js-tutorial-jsdeps.js:11914ReactMount.render @ scala-js-tutorial-jsdeps.js:11934React_render @ scala-js-tutorial-jsdeps.js:12864$c_Ltutorial_webapp_TutorialApp$.main__V @ TutorialApp.scala:15$c_Ltutorial_webapp_TutorialApp$.$$js$exported$meth$main__O @ JSApp.scala:18$c_Ltutorial_webapp_TutorialApp$.main @ TutorialApp.scala:14(anonymous function) @ scalajs-tutorial-fastopt.html:22

Not sure what's going wrong here?

**Comment by shadaj** [comment]
What version of Material Design Lite are you using? The location of the upgradeElement function has changed so you might need to upgrade.

**Comment by klappenbach** [comment]
I use the latest hosted one, straight from the MDL website:

```
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
<link rel="stylesheet" href="https://code.getmdl.io/1.1.3/material.indigo-pink.min.css">
<script defer src="https://code.getmdl.io/1.1.3/material.min.js"></script>
```

**Comment by shadaj** [comment]
The `defer` when loading MDL might be the issue. This library needs to use functions in MDL's JavaScript to upgrade MDL components once they are mounted, but looks like the Scala.js code is loaded before MDL is.

**Comment by klappenbach** [comment]
Yes removing `defer` solved the problem :)
`<script src="https://code.getmdl.io/1.1.3/material.min.js"></script>` works better and I no longer get the error in the browser! 👍
