### ISSUE TITLE
Example page throws TypeError

### ISSUE THREAD

**Issue by joprice** [payalabs/scalajs-react-mdl#3]
I see this error when loading the example page (http://payalabs.com/scalajs-react-mdl/):

`examples-opt.js:13Uncaught TypeError: Cannot read property 'componentHandler' of undefined`

**Comment by joprice** [comment]
It looks like the second reference to `componentHandler` is preceded by `Material`, which doesn't exist. https://github.com/payalabs/scalajs-react-mdl/blob/master/src/main/scala/com/payalabs/scalajs/react/mdl/MaterialComponent.scala#L24

**Comment by shadaj** [comment]
This was fixed by updating the version of MDL used.
